
-------------------------------------------------------------------------------
|        ..          ..                                                       |
|       ####*.      ####.                                                     |
|         `###*.       `#.              MSC Software                          |
|            `###.       #.             ------------                          |
|               `##.     ##                                                   |
|                 `##.   ##                                                   |
|                   `## ##'             A d a m s   C++   S o l v e r         |
|                     ####              Build:   2018.1.0-CL606746            |
|                     ###.              Version: Adams 2018.1 Student Edition |
|                    ###`#.                                                   |
|                  .###  `#                                                   |
|                 ####    `#                                                  |
|                ####      #.                                                 |
|              #####       `#           http://www.mscsoftware.com            |
|            .#####                                                           |
|           #####'                                                            |
|           ####                                                              |
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                      MSC Software Corporation                     *    |
|    *                                                                   *    |
|    *                             A d a m s                             *    |
|    *                                                                   *    |
|    *          Automatic Dynamic Analysis of Mechanical Systems         *    |
|    *                                                                   *    |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                         LEGAL INFORMATION                         *    |
|    *                                                                   *    |
|    *  Warning:  This computer  program is protected  by copyright law  *    |
|    *  and  international  treaties.    Unauthorized  reproduction  or  *    |
|    *  distribution  of this  computer program, or any  portion of it,  *    |
|    *  may result in severe civil and criminal penalties.               *    |
|    *                                                                   *    |
|    *  Copyright (C) 2018 MSC Software Corporation and  its licensors.  *    |
|    *                        All rights reserved.                       *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
|-----------------------------------------------------------------------------|
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *   Local Time: 2019-03-06 13:09:53                                 *    |
|    *    Host Name: LAPTOP-BA4FLL9Q                                     *    |
|    *        Uname: MS Windows NT                                       *    |
|    *      OS Info: 6.2                                                 *    |
|    *         User: Daniel                                              *    |
|    *  Customer ID: 9aa34d5b-GDC57950                                   *    |
|    *  Current dir: C:\Users\Daniel\Documents\GitKraken\DVA439-bicycle-balancing\simulations\Bicycle CAD + Simulation files\Simulation Files\Adams_model\12km Plant*    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
|                                                                             |
|-----------------------------------------------------------------------------|
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                          STUDENT EDITION                          *    |
|    *                                                                   *    |
|    *                       (Expires: 09-15-2020)                       *    |
|    *                                                                   *    |
|    *  This  Student  Edition is intended for use by eligible students  *    |
|    *                                                                   *    |
|    *  using   the  Software   for  educational   learning   purposes.  *    |
|    *                                                                   *    |
|    *  Commercial,  professional or other  for-profit use, or use  for  *    |
|    *                                                                   *    |
|    *  classroom   teaching  or  research  is  strictly    prohibited.  *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
-------------------------------------------------------------------------------

  OS-environment variable
  MDI_ADAMS_SCONTROLS_APPLICATION=1
  Adams Controls. Announces Adams Solver (C++) is being run with Adams Controls in either function evaluation mode or cosimulation mode.



-------------------------------------------------------------------------------
|                                 Model Title                                 |
|=============================================================================|
|                                                                             |
|                         SOLIDWORKS Motion Mechanism                         |
|                                                                             |
-------------------------------------------------------------------------------

 command: simulate/initial_conditions


  Begin Displacement Initial Conditions

  Time T=0.000000000E+00.
  Degree-of-freedom analysis identified redundant constraints in the model:
  -------------------------------------------------------------------------
   -  deactivating constraint equation  Zi.Yj in plant.Ground2Front
   -  deactivating constraint equation  Zi.Xj in plant.Ground2Front
   -  deactivating constraint equation  Zi.Yj in plant.Ground2Right
   -  deactivating constraint equation  Zi.Yj in plant.FrontWheel2Fork
   -  deactivating constraint equation  Zi.Xj in plant.FrontWheel2Fork
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1
   -  deactivating constraint equation  Zi.Yj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Zi.Xj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Si.Zj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Zi.Yj in plant.Fork2FrameCylinder
   -  deactivating constraint equation  Zi.Xj in plant.Fork2FrameCylinder
   -  deactivating constraint equation  Zi.Yj in plant.TorqueMotor.joi_rotor_stator
   -  deactivating constraint equation  Zi.Xj in plant.TorqueMotor.joi_rotor_stator
  Time T=0.000000000E+00.
  Degree-of-freedom analysis identified redundant constraints in the model:
  -------------------------------------------------------------------------
   -  deactivating constraint equation  Zi.Yj in plant.Ground2Front
   -  deactivating constraint equation  Zi.Xj in plant.Ground2Front
   -  deactivating constraint equation  Zi.Yj in plant.Ground2Right
   -  deactivating constraint equation  Zi.Yj in plant.FrontWheel2Fork
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1
   -  deactivating constraint equation  Zi.Yj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Zi.Xj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Si.Zj in plant.Fork2Frame_Bottom
   -  deactivating constraint equation  Zi.Yj in plant.Fork2FrameCylinder
   -  deactivating constraint equation  Zi.Xj in plant.Fork2FrameCylinder
   -  deactivating constraint equation  Zi.Xj in plant.FrontWheel2Frame
   -  deactivating constraint equation  Zi.Yj in plant.TorqueMotor.joi_rotor_stator
   -  deactivating constraint equation  Zi.Xj in plant.TorqueMotor.joi_rotor_stator

  End Displacement Initial Conditions


  Begin Velocity Initial Conditions


  End Velocity Initial Conditions


  Begin Acceleration Initial Conditions


  End Acceleration Initial Conditions


---- START: ERROR ----
PINPUT/0 is not defined in the data set. Command ignored.

---- END: ERROR ----
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   0.00000E+00  0.00000E+00            7            0       0            0.00 
   0.00000E+00  0.00000E+00            7            0       0            1.36 
   0.00000E+00  1.00000E-04            0            0       1            1.36 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   0.00000E+00  1.00000E-04            0            0       1            1.36 
   5.00000E-03  2.04666E-03           22            8       2            1.41 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.00000E-03  2.04666E-03           22            8       2            1.41 
   1.00000E-02  1.66667E-03           30           11       2            1.41 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.00000E-02  1.66667E-03           30           11       2            1.41 
   1.50000E-02  1.66667E-03           36           14       2            1.42 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.50000E-02  1.66667E-03           36           14       2            1.42 
   2.00000E-02  5.00000E-03           42           17       2            1.42 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.00000E-02  5.00000E-03           42           17       2            1.42 
   2.50000E-02  5.00000E-03           44           18       2            1.42 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.50000E-02  5.00000E-03           44           18       2            1.42 
   3.00000E-02  1.09777E-03           83           29       1            1.42 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.00000E-02  1.09777E-03           83           29       1            1.42 
   3.50000E-02  2.76261E-04          110           38       2            1.44 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.50000E-02  2.76261E-04          110           38       2            1.44 
   4.00000E-02  1.13809E-03          124           45       2            1.45 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.00000E-02  1.13809E-03          124           45       2            1.45 
   4.50000E-02  3.78140E-03          131           48       2            1.45 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.50000E-02  3.78140E-03          131           48       2            1.45 
   5.00000E-02  2.50000E-03          137           50       2            1.45 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.00000E-02  2.50000E-03          137           50       2            1.45 
   5.50000E-02  1.66667E-03          149           53       2            1.45 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.50000E-02  1.66667E-03          149           53       2            1.45 
   6.00000E-02  1.66667E-03          157           56       2            1.45 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   6.00000E-02  1.66667E-03          157           56       2            1.45 
   6.50000E-02  3.25516E-03          165           59       2            1.45 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   6.50000E-02  3.25516E-03          165           59       2            1.45 
   7.00000E-02  1.66667E-03          178           62       2            1.45 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   7.00000E-02  1.66667E-03          178           62       2            1.45 
   7.50000E-02  1.66667E-03          187           65       2            1.45 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   7.50000E-02  1.66667E-03          187           65       2            1.45 
   8.00000E-02  1.66667E-03          196           68       2            1.47 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   8.00000E-02  1.66667E-03          196           68       2            1.47 
   8.50000E-02  1.85767E-03          205           71       2            1.47 

  End Simulation
 command: var/21, fun=  1.23683906461390958e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   8.50000E-02  1.85767E-03          205           71       2            1.47 
   9.00000E-02  1.66667E-03          213           74       2            1.47 

  End Simulation
 command: var/21, fun= -1.16316093538609042e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  3.68390646139095668e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   9.00000E-02  1.66667E-03          213           74       2            1.47 
   9.50000E-02  2.12930E-03          225           78       2            1.50 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   9.50000E-02  2.12930E-03          225           78       2            1.50 
   1.00000E-01  1.66667E-03          232           81       2            1.50 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.00000E-01  1.66667E-03          232           81       2            1.50 
   1.05000E-01  3.33333E-03          236           83       2            1.52 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.05000E-01  3.33333E-03          236           83       2            1.52 
   1.10000E-01  1.66667E-03          248           86       2            1.52 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.10000E-01  1.66667E-03          248           86       2            1.52 
   1.15000E-01  1.66667E-03          255           89       2            1.53 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.15000E-01  1.66667E-03          255           89       2            1.53 
   1.20000E-01  1.84305E-03          264           92       2            1.53 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.20000E-01  1.84305E-03          264           92       2            1.53 
   1.25000E-01  1.66667E-03          271           95       2            1.55 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.25000E-01  1.66667E-03          271           95       2            1.55 
   1.30000E-01  1.66667E-03          280           98       2            1.55 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.30000E-01  1.66667E-03          280           98       2            1.55 
   1.35000E-01  1.66667E-03          288          101       2            1.56 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.35000E-01  1.66667E-03          288          101       2            1.56 
   1.40000E-01  1.92945E-03          296          104       3            1.56 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.40000E-01  1.92945E-03          296          104       3            1.56 
   1.45000E-01  1.66667E-03          305          107       3            1.58 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.45000E-01  1.66667E-03          305          107       3            1.58 
   1.50000E-01  8.33333E-04          318          111       3            1.58 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.50000E-01  8.33333E-04          318          111       3            1.58 
   1.55000E-01  8.33333E-04          331          117       1            1.59 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.55000E-01  8.33333E-04          331          117       1            1.59 
   1.60000E-01  8.33333E-04          343          123       1            1.61 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.60000E-01  8.33333E-04          343          123       1            1.61 
   1.65000E-01  1.66667E-03          353          127       2            1.63 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.65000E-01  1.66667E-03          353          127       2            1.63 
   1.70000E-01  1.66667E-03          362          130       2            1.63 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.70000E-01  1.66667E-03          362          130       2            1.63 
   1.75000E-01  1.91839E-03          371          133       2            1.64 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.75000E-01  1.91839E-03          371          133       2            1.64 
   1.80000E-01  1.66667E-03          379          136       2            1.64 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.80000E-01  1.66667E-03          379          136       2            1.64 
   1.85000E-01  1.49530E-03          393          140       2            1.66 

  End Simulation
 command: var/21, fun= -1.18017760772471014e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.85000E-01  1.49530E-03          393          140       2            1.66 
   1.90000E-01  1.41316E-03          405          144       2            1.66 

  End Simulation
 command: var/21, fun=  1.21982239227528986e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.98223922752897852e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.90000E-01  1.41316E-03          405          144       2            1.66 
   1.95000E-01  1.30450E-03          420          149       3            1.67 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   1.95000E-01  1.30450E-03          420          149       3            1.67 
   2.00000E-01  1.25000E-03          432          153       3            1.67 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.00000E-01  1.25000E-03          432          153       3            1.67 
   2.05000E-01  1.25000E-03          444          157       1            1.69 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.05000E-01  1.25000E-03          444          157       1            1.69 
   2.10000E-01  1.25000E-03          455          161       1            1.70 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.10000E-01  1.25000E-03          455          161       1            1.70 
   2.15000E-01  1.25000E-03          464          165       1            1.72 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.15000E-01  1.25000E-03          464          165       1            1.72 
   2.20000E-01  3.02384E-03          474          169       2            1.72 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.20000E-01  3.02384E-03          474          169       2            1.72 
   2.25000E-01  2.50000E-03          479          171       2            1.72 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.25000E-01  2.50000E-03          479          171       2            1.72 
   2.30000E-01  1.66667E-03          490          174       2            1.72 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.30000E-01  1.66667E-03          490          174       2            1.72 
   2.35000E-01  3.49623E-03          495          176       2            1.72 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.35000E-01  3.49623E-03          495          176       2            1.72 
   2.40000E-01  1.66667E-03          506          179       2            1.73 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.40000E-01  1.66667E-03          506          179       2            1.73 
   2.45000E-01  3.48289E-03          510          181       2            1.73 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.45000E-01  3.48289E-03          510          181       2            1.73 
   2.50000E-01  1.66667E-03          522          184       2            1.75 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.50000E-01  1.66667E-03          522          184       2            1.75 
   2.55000E-01  3.50092E-03          527          186       2            1.77 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.55000E-01  3.50092E-03          527          186       2            1.77 
   2.60000E-01  1.66667E-03          539          189       2            1.77 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.60000E-01  1.66667E-03          539          189       2            1.77 
   2.65000E-01  1.66667E-03          548          192       1            1.77 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.65000E-01  1.66667E-03          548          192       1            1.77 
   2.70000E-01  3.33333E-03          554          194       2            1.77 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.70000E-01  3.33333E-03          554          194       2            1.77 
   2.75000E-01  1.66667E-03          565          197       2            1.78 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.75000E-01  1.66667E-03          565          197       2            1.78 
   2.80000E-01  3.47343E-03          570          199       2            1.78 

  End Simulation
 command: var/21, fun=  1.20237424295859228e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.80000E-01  3.47343E-03          570          199       2            1.78 
   2.85000E-01  2.50000E-03          574          201       2            1.80 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.85000E-01  2.50000E-03          574          201       2            1.80 
   2.90000E-01  1.66667E-03          586          204       2            1.80 

  End Simulation
 command: var/21, fun= -1.19762575704140772e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  2.37424295859223061e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.90000E-01  1.66667E-03          586          204       2            1.80 
   2.95000E-01  3.51840E-03          592          206       2            1.81 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   2.95000E-01  3.51840E-03          592          206       2            1.81 
   3.00000E-01  1.66667E-03          603          209       2            1.81 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.00000E-01  1.66667E-03          603          209       2            1.81 
   3.05000E-01  1.66667E-03          612          212       1            1.83 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.05000E-01  1.66667E-03          612          212       1            1.83 
   3.10000E-01  1.66667E-03          619          215       2            1.84 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.10000E-01  1.66667E-03          619          215       2            1.84 
   3.15000E-01  1.96574E-03          628          218       2            1.84 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.15000E-01  1.96574E-03          628          218       2            1.84 
   3.20000E-01  1.66667E-03          637          221       2            1.84 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.20000E-01  1.66667E-03          637          221       2            1.84 
   3.25000E-01  3.02603E-03          649          225       2            1.84 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.25000E-01  3.02603E-03          649          225       2            1.84 
   3.30000E-01  1.66667E-03          661          228       2            1.86 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.30000E-01  1.66667E-03          661          228       2            1.86 
   3.35000E-01  3.43446E-03          667          230       2            1.86 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.35000E-01  3.43446E-03          667          230       2            1.86 
   3.40000E-01  2.50000E-03          672          232       2            1.88 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.40000E-01  2.50000E-03          672          232       2            1.88 
   3.45000E-01  1.66667E-03          684          235       2            1.88 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.45000E-01  1.66667E-03          684          235       2            1.88 
   3.50000E-01  1.66667E-03          693          238       1            1.89 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.50000E-01  1.66667E-03          693          238       1            1.89 
   3.55000E-01  3.33333E-03          699          240       2            1.89 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.55000E-01  3.33333E-03          699          240       2            1.89 
   3.60000E-01  1.66667E-03          710          243       2            1.89 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.60000E-01  1.66667E-03          710          243       2            1.89 
   3.65000E-01  3.39464E-03          715          245       2            1.89 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.65000E-01  3.39464E-03          715          245       2            1.89 
   3.70000E-01  2.50000E-03          719          247       2            1.91 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.70000E-01  2.50000E-03          719          247       2            1.91 
   3.75000E-01  1.66667E-03          731          250       2            1.91 

  End Simulation
 command: var/21, fun= -1.18888121346214106e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.75000E-01  1.66667E-03          731          250       2            1.91 
   3.80000E-01  3.44478E-03          736          252       2            1.92 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.80000E-01  3.44478E-03          736          252       2            1.92 
   3.85000E-01  1.66667E-03          749          255       2            1.92 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.85000E-01  1.66667E-03          749          255       2            1.92 
   3.90000E-01  3.33333E-03          754          257       2            1.94 

  End Simulation
 command: var/21, fun=  1.21111878653785894e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.11187865378589407e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.90000E-01  3.33333E-03          754          257       2            1.94 
   3.95000E-01  2.50000E-03          758          259       2            1.94 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   3.95000E-01  2.50000E-03          758          259       2            1.94 
   4.00000E-01  5.00000E-03          762          261       2            1.95 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.00000E-01  5.00000E-03          762          261       2            1.95 
   4.05000E-01  1.66667E-03          774          264       2            1.95 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.05000E-01  1.66667E-03          774          264       2            1.95 
   4.10000E-01  1.66667E-03          780          267       2            1.97 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.10000E-01  1.66667E-03          780          267       2            1.97 
   4.15000E-01  3.62388E-03          786          270       2            1.97 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.15000E-01  3.62388E-03          786          270       2            1.97 
   4.20000E-01  2.50000E-03          791          272       2            1.98 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.20000E-01  2.50000E-03          791          272       2            1.98 
   4.25000E-01  5.00000E-03          796          274       2            1.98 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.25000E-01  5.00000E-03          796          274       2            1.98 
   4.30000E-01  1.66667E-03          812          277       2            2.00 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.30000E-01  1.66667E-03          812          277       2            2.00 
   4.35000E-01  3.33333E-03          817          279       2            2.00 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.35000E-01  3.33333E-03          817          279       2            2.00 
   4.40000E-01  1.66667E-03          829          282       2            2.02 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.40000E-01  1.66667E-03          829          282       2            2.02 
   4.45000E-01  3.34763E-03          835          284       2            2.02 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.45000E-01  3.34763E-03          835          284       2            2.02 
   4.50000E-01  2.50000E-03          839          286       2            2.03 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.50000E-01  2.50000E-03          839          286       2            2.03 
   4.55000E-01  1.66667E-03          851          289       2            2.03 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.55000E-01  1.66667E-03          851          289       2            2.03 
   4.60000E-01  3.33333E-03          856          291       2            2.05 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.60000E-01  3.33333E-03          856          291       2            2.05 
   4.65000E-01  2.50000E-03          860          293       2            2.05 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.65000E-01  2.50000E-03          860          293       2            2.05 
   4.70000E-01  1.66667E-03          871          296       2            2.06 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.70000E-01  1.66667E-03          871          296       2            2.06 
   4.75000E-01  3.33333E-03          876          298       2            2.06 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.75000E-01  3.33333E-03          876          298       2            2.06 
   4.80000E-01  1.66667E-03          887          301       2            2.08 

  End Simulation
 command: var/21, fun= -1.22202566029975355e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.80000E-01  1.66667E-03          887          301       2            2.08 
   4.85000E-01  1.66667E-03          895          304       1            2.08 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.85000E-01  1.66667E-03          895          304       1            2.08 
   4.90000E-01  3.42520E-03          908          308       2            2.09 

  End Simulation
 command: var/21, fun=  1.17797433970024645e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun= -2.20256602997535356e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.90000E-01  3.42520E-03          908          308       2            2.09 
   4.95000E-01  2.50000E-03          913          310       2            2.09 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   4.95000E-01  2.50000E-03          913          310       2            2.09 
   5.00000E-01  1.66667E-03          925          313       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.00000E-01  1.66667E-03          925          313       2            2.11 
   5.05000E-01  3.33333E-03          930          315       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.05000E-01  3.33333E-03          930          315       2            2.11 
   5.10000E-01  2.50000E-03          934          317       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.10000E-01  2.50000E-03          934          317       2            2.11 
   5.15000E-01  5.00000E-03          939          319       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.15000E-01  5.00000E-03          939          319       2            2.11 
   5.20000E-01  5.00000E-03          942          320       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.20000E-01  5.00000E-03          942          320       2            2.11 
   5.25000E-01  5.00000E-03          945          321       2            2.11 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.25000E-01  5.00000E-03          945          321       2            2.11 
   5.30000E-01  5.00000E-03          948          322       2            2.13 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.30000E-01  5.00000E-03          948          322       2            2.13 
   5.35000E-01  5.00000E-03          950          323       2            2.13 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.35000E-01  5.00000E-03          950          323       2            2.13 
   5.40000E-01  5.00000E-03          953          324       2            2.14 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.40000E-01  5.00000E-03          953          324       2            2.14 
   5.45000E-01  1.66667E-03          965          327       2            2.14 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.45000E-01  1.66667E-03          965          327       2            2.14 
   5.50000E-01  1.66667E-03          973          330       2            2.14 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.50000E-01  1.66667E-03          973          330       2            2.14 
   5.55000E-01  3.33333E-03          978          332       2            2.14 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.55000E-01  3.33333E-03          978          332       2            2.14 
   5.60000E-01  1.66667E-03          989          335       2            2.16 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.60000E-01  1.66667E-03          989          335       2            2.16 
   5.65000E-01  1.66667E-03          995          338       2            2.16 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.65000E-01  1.66667E-03          995          338       2            2.16 
   5.70000E-01  2.13985E-03         1003          341       1            2.17 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.70000E-01  2.13985E-03         1003          341       1            2.17 
   5.75000E-01  2.39559E-03         1011          344       2            2.19 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.75000E-01  2.39559E-03         1011          344       2            2.19 
   5.80000E-01  1.66667E-03         1022          347       2            2.19 

  End Simulation
 command: var/21, fun= -1.14636326524670942e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.80000E-01  1.66667E-03         1022          347       2            2.19 
   5.85000E-01  1.66667E-03         1029          350       2            2.20 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.85000E-01  1.66667E-03         1029          350       2            2.20 
   5.90000E-01  1.66667E-03         1037          353       2            2.20 

  End Simulation
 command: var/21, fun=  1.25363673475329058e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  5.36367347532905714e-01


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.90000E-01  1.66667E-03         1037          353       2            2.20 
   5.95000E-01  1.66667E-03         1043          356       2            2.20 

  End Simulation
 command: var/21, fun=  1.20186763416524922e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.86763416524929754e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   5.95000E-01  1.66667E-03         1043          356       2            2.20 
   6.00000E-01  4.26104E-03         1049          359       2            2.22 

  End Simulation
 command: var/21, fun= -1.19813236583475078e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.86763416524929754e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   6.00000E-01  4.26104E-03         1049          359       2            2.22 
   6.05000E-01  1.66667E-03         1059          362       2            2.22 

  End Simulation
 command: var/21, fun=  1.20186763416524922e+01
 command: var/5, fun=  9.55000000000000071e+00
 command: var/25, fun=  1.86763416524929754e-02


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = modified
   Integration error =    1.000000E-04

   Simulation      Step        Function    Cumulative   Integration     CPU
      Time         Size       Evaluations  Steps Taken    Order        time
   ___________  ___________   ___________  ___________   _________    ________
   6.05000E-01  1.66667E-03         1059          362       2            2.22 
   6.10000E-01  1.66667E-03         1067          365       2            2.22 

  End Simulation


Finished -----
Elapsed time = 3.68s,  CPU time = 2.23s,  60.78%

