clear adapting
clear best_net
clear currentState
clear nextState
clear experience_count
clear exploration
clear fails
clear k
clear most_steps
clear net_input
clear net_output
clear new_experience
clear nextState
clear Q
clear Q_index
clear rand_nr
clear stepz
clear tmp
clear total
clear net
clear episode
clear experience